spring:
  application:
    name: browser-task
server:
  port: 7171
  servlet:
    context-path: /browser-task

system:
  id: "${REALM:browser-task}"
  virtual-url: "${VIRTUAL_URL: your virtual config url here}"
  config-url: "${CONFIG_URL: your url to load firebase config}"
  profile-table-url: "${PROFILE_TABLE_URL: your url to save profile after login success}"