spring:
  application:
    name: browser-task
server:
  port: 7171
  servlet:
    context-path: /browser-task

firebase:
   collection-name: "${FIREBASE_COLLECTION_NAME:browser-task}"
system:
  id: "${REALM:browser-task}"
  virtual-url: "${VIRTUAL_URL: your virtual config url here}"
  config-url: "${CONFIG_URL: your config url}"