spring:
  application:
    name: browser-task
  task:
    scheduling:
      pool:
        size: 10
    execution:
      pool:
        core-size: 64
server:
  port: 7171
  servlet:
    context-path: /browser-task

system:
  id: "${REALM:browser-task}"
  virtual-url: "${VIRTUAL_URL: your virtual config url here}"
  database-json-url: "${DATABASE_JSON_URL:***onpet.vn/public/api/dynamic/table}"
  socket-url: "${SOCKET_URL:***moonpet.vn/ws}"
  socket-destination: "${SOCKET_DESTINATION:/topic/messages/browser-task}"
  socket-push-url: "${SOCKET_PUSH_URL:***/api/notification/push}"

github:
  api-url: "${GITHUB_API_URL:https://api.github.com/repos/{{owner}}/{{repo_name}}/contents}"
  token: "${GITHUB_TOKEN: your github token}"

logging:
  file:
    name: log/browser-task.log
  logback:
    rollingpolicy:
      max-history: 2
