spring:
  application:
    name: browser-task
server:
  port: 7171
  servlet:
    context-path: /browser-task

firebase:
   database-url: "${FIREBASE_DATABASE_URL:https://zone13-d5304-default-rtdb.asia-southeast1.firebasedatabase.app}"
   collection-name: "${FIREBASE_COLLECTION_NAME:browser-task}"
